name: Playwright Phase1 Tests

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  playwright:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        node-version: [18.x]
        python-version: ['3.10']
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r server/requirements.txt

      - name: Start backend (uvicorn)
        run: |
          nohup python -m uvicorn server.app.main:app --host 127.0.0.1 --port 8000 > server.log 2>&1 &
          for i in {1..30}; do
            if curl -sS http://127.0.0.1:8000/api/health >/dev/null 2>&1; then echo "backend up"; break; fi
            echo "waiting for backend..."
            sleep 1
          done

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Playwright
        run: |
          npm ci || npm i -D @playwright/test
          npx playwright install --with-deps

      - name: Run Playwright tests
        run: |
          npx playwright test --project=chromium --reporter=list,html

      - name: Upload Playwright HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          if-no-files-found: warn
          retention-days: 30
